SHOW_FPS = True
SHOW_MINI_DISPLAY = True
USE_KEYBOARD = False # SHOW_MINI_DISPLAY must be enabled for inputs
RENDER_MODE = "human" # [human | none]
EPSILON_MIN = 0.05
EPSILON_START = 0.05
EPSILON_SCALING = 0.999995
MAX_STUCK_TIME = 1000
ENABLE_TRAINING = False
BUFFER_LENGTH = 60*2
STAND_STILL_PENALTY = -2

SPEEDRUN_ACTIONS = [
    0,
    2,
    4,
]
