SHOW_FPS = True
AVERAGE_FPS_CALCULATION_TIME = 20
MAX_FRAMERATE = 99999999

SHOW_MINI_DISPLAY = False
USE_KEYBOARD = False # SHOW_MINI_DISPLAY must be enabled for inputs
RENDER_MODE = "none" # [human | none]
EPSILON_MIN = 0.01
EPSILON_START = 0.01
EPSILON_SCALING = 0.9999
GAMMA = 0.9
ALPHA = 0.1

MAX_STUCK_TIME = 1000
ENABLE_TRAINING = True
STAND_STILL_PENALTY = -2
VISION_RANGE = 6

FRAMES_BEFORE_UPDATE = 60//4

SPEEDRUN_ACTIONS = [
    3,
    4,
]

IDLE_ACTION = 0
