SHOW_FPS = False
SHOW_MINI_DISPLAY = True
USE_KEYBOARD = False # SHOW_MINI_DISPLAY must be enabled for inputs
RENDER_MODE = "none" # [human | none]
EPSILON_MIN = 0.001
EPSILON_START = 1
EPSILON_SCALING = 0.99990
MAX_STUCK_TIME = 1000
ENABLE_TRAINING = True
BUFFER_LENGTH = 60*2
STAND_STILL_PENALTY = -2
VISION_RANGE = 6
SPEEDRUN_ACTIONS = [
    0,
    2,
    4,
]
